# Generated by Django 3.2 on 2021-05-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210519_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='date_purchased',
        ),
        migrations.AddField(
            model_name='gear',
            name='photo',
            field=models.ImageField(default='static/images/upload_photo.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='gear',
            name='slug',
            field=models.SlugField(default='somestring', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.category')),
            ],
        ),
        migrations.AddField(
            model_name='gear',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
    ]
