# Generated by Django 3.2 on 2021-05-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210520_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
