# Generated by Django 3.2 on 2021-05-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0005_alter_user_id'),
        ('dashboard', '0008_auto_20210521_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(related_name='trips', to='loginReg.User'),
        ),
    ]
