# Generated by Django 3.2 on 2021-05-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_trip_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='trips',
            field=models.ManyToManyField(related_name='trip_gear', to='dashboard.Trip'),
        ),
    ]
