# Generated by Django 3.2 on 2021-05-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_gear_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(choices=[('Water', (('filter', 'Filter'), ('water', 'Water'))), ('Shelter', (('tent', 'Tent'), ('tarp', 'Tarp/Rainfly'))), ('Sleep', (('bag', 'Sleeping Bag'), ('pad', 'Sleeping Pad'))), ('Cooking', (('stove', 'Stove'), ('fuel', 'Fuel'))), ('food', 'Food'), ('Clothes', (('pants', 'Pants'), ('shirt', 'Shirt'), ('jacket', 'Jacket')))], default='water', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
