# Generated by Django 3.2 on 2021-05-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0005_alter_user_id'),
        ('dashboard', '0015_alter_gear_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_gear', to='loginReg.user'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
