# Generated by Django 3.2 on 2021-05-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210522_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
