# Generated by Django 3.1.6 on 2021-05-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
